[package]
name = "secret_sharing_spring2020"
version = "0.1.0"
authors = ["Daniel Owens"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
bitreader = "0.3.2"